RestaurantManagementSystems/Models/OrderSystem/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RestaurantManagementSystems.Models
{
    public class Order
    {
        public enum PaymentTypes
        {
            Pre, Post
        }

        public enum PaymentModes
        {
            Cash, Card
        }

        public enum OrderStatus
        {
            InProcess, Deliverd
        }
        
        [Key]
        public int OrderID { get; set; }

        [StringLength(50, MinimumLength = 3)]
        public string PersonName { get; set; }

        [DataType(DataType.Currency)]
        //[Column(TypeName = "total money")]
        public decimal TotalAmount { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "order date")]
        public DateTime OrderDate { get; set; }

        //pre or post
        [DisplayFormat(NullDisplayText = "Pre")]
        public PaymentTypes? PaymentType { get; set; }
        
        //cash or card
        [DisplayFormat(NullDisplayText = "Cash")]
        public PaymentModes? PaymentMode { get; set; }


        //InProcess or Deliverd
        [DisplayFormat(NullDisplayText = "InProcess")]
        public OrderStatus Orderstatus { get; set; }

        public List<OrderDetail> OrderItem { get; set; }

    }

    

}

RestaurantManagementSystems/Controllers/OrderDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RestaurantManagementSystems.Data;
using RestaurantManagementSystems.Models;

namespace RestaurantManagementSystems.Controllers
{
    public class OrderDetailsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrderDetailsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: OrderDetails
        public async Task<IActionResult> Report()
        {
            //var applicationDbContext = _context.OrderItems.Include(o => o.Menus).Include(o => o.Order);
            
            return View("Report");
        }

        // GET: OrderDetails
        public async Task<IActionResult> Reporting()
        {
            //var applicationDbContext = _context.OrderItems.Include(o => o.Menus).Include(o => o.Order).Select(m => m.Order.OrderDate.Date == DateTime.Today.Date);

            //var v = _context.OrderItems.Select(m => m.Order.OrderDate.Date == DateTime.Today.Date);
            var query = from c in _context.OrderItems.Where(m => m.Order.OrderDate.Date == DateTime.Today.Date)
                        group c by c.Menus.Name into g
                        select new
                        {
                            MenuName = g.Key,
                            //MenuName = g.Select(p => p.Menus.Name) ,
                            NoOfOrder = g.Select(m => m.Quantity).Sum(),
                            UnitPrice = g.Select(n => n.UnitPrice).Take(1)
                        };


            return Json(query);
        }

        // GET: OrderDetails
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.OrderItems.Include(o => o.Menus).Include(o => o.Order);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: OrderDetails
        public async Task<IActionResult> Index1(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var applicationDbContext = _context.OrderItems.ToListAsync().Result.AsQueryable().Where(m => m.OrderID == id);
            return View(applicationDbContext.ToList());
        }

        // GET: OrderDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderDetail = await _context.OrderItems
                .Include(o => o.Menus)
                .Include(o => o.Order)
                .FirstOrDefaultAsync(m => m.OrderItemID == id);
            if (orderDetail == null)
            {
                return NotFound();
            }

            return View(orderDetail);
        }

        // GET: OrderDetails/Create
        public IActionResult Create()
        {
            ViewData["MenuItemID"] = new SelectList(_context.MenuItmes, "MenuID", "MenuID");
            ViewData["OrderID"] = new SelectList(_context.Orders, "OrderID", "OrderID");
            return View();
        }

        // POST: OrderDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderItemID,OrderID,MenuItemID,UnitPrice,Quantity")] OrderDetail orderDetail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orderDetail);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MenuItemID"] = new SelectList(_context.MenuItmes, "MenuID", "MenuID", orderDetail.MenuItemID);
            ViewData["OrderID"] = new SelectList(_context.Orders, "OrderID", "OrderID", orderDetail.OrderID);
            return View(orderDetail);
        }

        // GET: OrderDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderDetail = await _context.OrderItems.FindAsync(id);
            if (orderDetail == null)
            {
                return NotFound();
            }
            ViewData["MenuItemID"] = new SelectList(_context.MenuItmes, "MenuID", "MenuID", orderDetail.MenuItemID);
            ViewData["OrderID"] = new SelectList(_context.Orders, "OrderID", "OrderID", orderDetail.OrderID);
            return View(orderDetail);
        }

        // POST: OrderDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderItemID,OrderID,MenuItemID,UnitPrice,Quantity")] OrderDetail orderDetail)
        {
            if (id != orderDetail.OrderItemID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orderDetail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderDetailExists(orderDetail.OrderItemID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MenuItemID"] = new SelectList(_context.MenuItmes, "MenuID", "MenuID", orderDetail.MenuItemID);
            ViewData["OrderID"] = new SelectList(_context.Orders, "OrderID", "OrderID", orderDetail.OrderID);
            return View(orderDetail);
        }

        // GET: OrderDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderDetail = await _context.OrderItems
                .Include(o => o.Menus)
                .Include(o => o.Order)
                .FirstOrDefaultAsync(m => m.OrderItemID == id);
            if (orderDetail == null)
            {
                return NotFound();
            }

            return View(orderDetail);
        }

        // POST: OrderDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var orderDetail = await _context.OrderItems.FindAsync(id);
            _context.OrderItems.Remove(orderDetail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderDetailExists(int id)
        {
            return _context.OrderItems.Any(e => e.OrderItemID == id);
        }
    }
}

RestaurantManagementSystems/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RestaurantManagementSystems.Data;
using RestaurantManagementSystems.Models;

namespace RestaurantManagementSystems.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrdersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index1()
        {

          

            return View(_context.Orders.ToListAsync().Result.FindAll(m => m.OrderDate.Date == DateTime.Today.Date));



        }

        // GET: Orders Total
        public async Task<IActionResult> OrderTotal()
        {
            var v= _context.Orders.ToListAsync().Result.AsQueryable().Where(m => m.OrderDate.Date == DateTime.Today.Date).Sum(m => m.TotalAmount);
           // Array a = new Array[];
            return Json(v);
        }

        // GET: Orders Total
        public async Task<IActionResult> HourlyOrderTotal()
        {
            var v = _context.Orders.ToListAsync().Result.AsQueryable().GroupBy(m => m.OrderDate.Date.Hour);
            // Array a = new Array[];
            var query = from c in _context.Orders//.Where(m => m.OrderDate.Date == DateTime.Today.Date)
                        group c by c.OrderDate.Hour into g
                        select new
                        {
                            Hour = g.Key,
                            //MenuName = g.Select(p => p.Menus.Name) ,
                            NoOfOrder = g.Count(),
                            //OrderTotal = g.Sum(n => n.UnitPrice)
                        };


            return Json(query);
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            return View(await _context.Orders.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderID,PersonName,TotalAmount,OrderDate,PaymentType,PaymentMode,Orderstatus")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderID,PersonName,TotalAmount,OrderDate,PaymentType,PaymentMode,Orderstatus")] Order order)
        {
            if (id != order.OrderID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.OrderID == id);
        }
    }
}

RestaurantManagementSystems/Views/Orders/Create.cshtml
@model RestaurantManagementSystems.Models.Order

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PersonName" class="control-label"></label>
                <input asp-for="PersonName" class="form-control" />
                <span asp-validation-for="PersonName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalAmount" class="control-label"></label>
                <input asp-for="TotalAmount" class="form-control" />
                <span asp-validation-for="TotalAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentType" class="control-label"></label>
                <input asp-for="PaymentType" class="form-control" />
                <span asp-validation-for="PaymentType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentMode" class="control-label"></label>
                <input asp-for="PaymentMode" class="form-control" />
                <span asp-validation-for="PaymentMode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Orderstatus" class="control-label"></label>
                <select asp-for="Orderstatus" class="form-control"></select>
                <span asp-validation-for="Orderstatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

RestaurantManagementSystems/Views/Orders/Delete.cshtml
@model RestaurantManagementSystems.Models.Order

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PersonName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PersonName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TotalAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TotalAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PaymentType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PaymentType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PaymentMode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PaymentMode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Orderstatus)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Orderstatus)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OrderID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RestaurantManagementSystems/Views/Orders/Details.cshtml
@model RestaurantManagementSystems.Models.Order

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PersonName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PersonName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TotalAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TotalAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PaymentType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PaymentType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PaymentMode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PaymentMode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Orderstatus)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Orderstatus)
        </dd>
    </dl>
</div>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model.OrderID">Edit</a>*@
    @Html.ActionLink("Get Order Items ", "Index1", "OrderDetails", new { id = Model.OrderID })|
    <a asp-action="Index1"> Back to Todays Order List </a>|
    <a asp-action="Index"> Back to All Order List </a>|

</div>
@*<table class="table">
    <thead>
        <tr>
            <th>
                UnitPrice
            </th>
            <th>
                Quantity
            </th>
            <th>
                Menus
            </th>
            <th>
                Order
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.OrderItem)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UnitPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Menus.MenuID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Order.OrderID)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.OrderItemID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.OrderItemID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.OrderItemID">Delete</a>
                </td>
            </tr>
           
        }
    </tbody>
</table>*@

RestaurantManagementSystems/Views/Orders/Edit.cshtml
@model RestaurantManagementSystems.Models.Order

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderID" />
            <div class="form-group">
                <label asp-for="PersonName" class="control-label"></label>
                <input asp-for="PersonName" class="form-control" />
                <span asp-validation-for="PersonName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalAmount" class="control-label"></label>
                <input asp-for="TotalAmount" class="form-control" />
                <span asp-validation-for="TotalAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentType" class="control-label"></label>
                <input asp-for="PaymentType" class="form-control" />
                <span asp-validation-for="PaymentType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentMode" class="control-label"></label>
                <input asp-for="PaymentMode" class="form-control" />
                <span asp-validation-for="PaymentMode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Orderstatus" class="control-label"></label>
                <select asp-for="Orderstatus" class="form-control"></select>
                <span asp-validation-for="Orderstatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

RestaurantManagementSystems/Views/Orders/Index.cshtml
@model IEnumerable<RestaurantManagementSystems.Models.Order>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PersonName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentMode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Orderstatus)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PersonName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentMode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Orderstatus)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.OrderID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.OrderID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.OrderID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

RestaurantManagementSystems/Views/Orders/Index1.cshtml
@model IEnumerable<RestaurantManagementSystems.Models.Order>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>
<script>
    $(document).ready(function () {
        $.post("/Orders/OrderTotal",
            function (data) {

                // Successful requests get here
                // Update the page elements
                //var data = JSON.parse(data1);
                //alert(data.cartTotal);
                //if (data.itemCount == 0) {
                //    $('#row-' + data.deleteId).fadeOut('slow');
                //    //alert("Hiderow");
                //} else {
                //    //alert(data.itemCount);
                //    $('#item-count-' + data.deleteId).text(data.itemCount);
                //}
                $('#cart-total').text('TOTAL ORDER AMOUNT FOR TODAY IS: ' + data);
                //alert(data.message);
                //$('#update-message').text(data.message);
                ////alert(data.cartCount);
                //$('#contentcart a').text('Cart (' + data.cartCount + ')');
            });
    });
</script>
<p>
    <div id="cart-total" style="font-size:larger;font-weight:bold"></div>
    @*<a asp-action="Create">Create New</a>*@
</p>
@Html.ActionLink("Report ", "Report", "OrderDetails")
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PersonName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentMode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Orderstatus)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PersonName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalAmount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PaymentType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PaymentMode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Orderstatus)
                </td>
                <td>
                    @*<a asp-action="Edit" asp-route-id="@item.OrderID">Edit</a>*@ |
                    <a asp-action="Details" asp-route-id="@item.OrderID">Details</a> |
                    @*<a asp-action="Delete" asp-route-id="@item.OrderID">Delete</a>*@
                </td>
            </tr>
        }
    </tbody>
</table>