RestaurantManagementSystems/Controllers/CheckoutController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RestaurantManagementSystems.Models;
using RestaurantManagementSystems.Data;


namespace RestaurantManagementSystems.Controllers
{
[Authorize]
public class CheckoutController : Controller
{
        private readonly ApplicationDbContext storeDB;

        public CheckoutController(ApplicationDbContext context)
        {
            storeDB = context;
        }

        //ApplicationDbContext storeDB;
        const string PromoCode = "FREE";
        //
        // GET: /Checkout/AddressAndPayment
        public ActionResult AddressAndPayment()
        {
                return View();
        }
        //
        // POST: /Checkout/AddressAndPayment
        [HttpPost]
        public ActionResult AddressAndPayment(IFormCollection values)
        {
                var order = new Order();
                TryUpdateModelAsync(order);
                try
                {
                    if (string.Equals(values["PromoCode"], PromoCode,
                    StringComparison.OrdinalIgnoreCase) == false)
                    {
                        return View(order);
                    }
                    else
                    {
                        order.PersonName = User.Identity.Name;
                        order.OrderDate = DateTime.Now;
                        //Save Order
                        storeDB.Orders.Add(order);
                        storeDB.SaveChanges();
                        //Process the order
                        var cart = ShoppingCart.GetCart(this.HttpContext,storeDB);
                        cart.CreateOrder(order,storeDB);
                        return RedirectToAction("Complete", new { id = order.OrderID });
                    }
                }
                catch
                {
                    //Invalid - redisplay with errors
                    return View(order);
                }
        }
        //
        // GET: /Checkout/Complete
        public ActionResult Complete(int id)
        {
            // Validate customer owns this order
            bool isValid = storeDB.Orders.Any(
            o => o.OrderID == id &&
            o.PersonName == User.Identity.Name);
            if (isValid)
            {
                return View(id);
            }
            else
            {
                return View("Error");
            }

        }
}
}

RestaurantManagementSystems/Controllers/MenuItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RestaurantManagementSystems.Data;
using RestaurantManagementSystems.Models;

namespace RestaurantManagementSystems.Controllers
{
    public class MenuItemsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MenuItemsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: MenuItems
        public async Task<IActionResult> Index()
        {
            return View(await _context.MenuItmes.ToListAsync());
        }

        // GET: MenuItems
        public async Task<IActionResult> Pricing()
        {
            return View(await _context.MenuItmes.ToListAsync());
        }

        // GET: MenuItems
        public async Task<IActionResult> Index1()
        {
            return View( _context.MenuItmes.ToListAsync().Result.FindAll(m => m.TodaysMenu.Value == MenuItem.InTodaysMenu.Yes));
        }


        // GET: MenuItems/GetMenus
        public async Task<IActionResult> GetMenus()
        {
            return PartialView(await _context.MenuItmes.ToListAsync());
        }


        // GET: MenuItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menuItem = await _context.MenuItmes
                .FirstOrDefaultAsync(m => m.MenuID == id);
            if (menuItem == null)
            {
                return NotFound();
            }

            return View(menuItem);
        }

        // GET: MenuItems/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MenuItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MenuID,Name,Price,Ingridents,recipe,ImageUrl,TodaysMenu")] MenuItem menuItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(menuItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(menuItem);
        }

        // GET: MenuItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menuItem = await _context.MenuItmes.FindAsync(id);
            if (menuItem == null)
            {
                return NotFound();
            }
            return View(menuItem);
        }

        // POST: MenuItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MenuID,Name,Price,Ingridents,recipe,ImageUrl,TodaysMenu")] MenuItem menuItem)
        {
            if (id != menuItem.MenuID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(menuItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MenuItemExists(menuItem.MenuID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(menuItem);
        }

        // GET: MenuItems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menuItem = await _context.MenuItmes
                .FirstOrDefaultAsync(m => m.MenuID == id);
            if (menuItem == null)
            {
                return NotFound();
            }

            return View(menuItem);
        }

        // POST: MenuItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var menuItem = await _context.MenuItmes.FindAsync(id);
            _context.MenuItmes.Remove(menuItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MenuItemExists(int id)
        {
            return _context.MenuItmes.Any(e => e.MenuID == id);
        }
    }
}

RestaurantManagementSystems/Views/Checkout/AddressAndPayment.cshtml
@model RestaurantManagementSystems.Models.Order
@{
    ViewBag.Title = "Address And Payment"; }
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script>
    $(document).ready(function () {
        $('td').each(function (index) {
            //alert(index);
            //var tds = td.find("td[id='11']");
            //tds.hide();
            $('.RemoveLink').hide();
            //tr.find("td[id='11']");
        });
        $('#22').hide();
        
            //alert(8);
        //if ($("#cart-total").val() != 0) {

        //    //alert(33);
            
        //}
        //else { $('#order').hide();}

        
    });

    function printdiv(printpage) {
        var headstr = "<html><head><title></title></head><body>";
        var footstr = "</body>";
        var newstr = document.all.item(printpage).innerHTML;
        var oldstr = document.body.innerHTML;
        document.body.innerHTML = headstr + newstr + footstr;
        window.print();
        document.body.innerHTML = oldstr;
        return false;
    }
    //function CallPrint(strid) {
    //    var prtContent = document.getElementById(strid);
    //    var WinPrint = window.open('', '', 'letf=0,top=0,width=800,height=100,toolbar=0,scrollbars=0,status=0,dir=ltr');
    //    WinPrint.document.write(prtContent.innerHTML);
    //    WinPrint.document.close();
    //    WinPrint.focus();
    //    WinPrint.print();
    //    WinPrint.close();
    //    prtContent.innerHTML = strOldOne;
    //}
</script>
@using (Html.BeginForm())
{

    <h2>@*Address And Payment*@</h2>
    <div id="div_print" style="width:500px">

        @await Component.InvokeAsync("CartView", new { maxPriority = 4, isDone = true })

    </div>
    @*<input name="b_print" type="button" class="ipt" onClick="printdiv('div_print');" value=" Print ">*@
    @*<asp:button id="BtnPrint" runat="server" onclientclick="javascript:CallPrint('bill');" text="Print" xmlns:asp="#unknown" />*@
    <fieldset>
        <legend></legend>
        @*@Html.EditorForModel()*@
    </fieldset>
    <fieldset>
        <legend>Payment</legend>
        <p>We're running a promotion: all music is free with the promo code: "FREE"</p>
        <div class="editor-label">
            @Html.Label("Promo Code")
        </div>
        <div class="editor-field">
            @Html.TextBox("PromoCode", "FREE")
        </div>
    </fieldset>
    <input type="submit" id="order" value="Submit Order" onClick="printdiv('div_print');" />
}

RestaurantManagementSystems/Views/Checkout/Complete.cshtml
@model int

@{
    ViewBag.Title = "Checkout Complete"; }
<h2>Checkout Complete</h2>
<p>Thanks for your order! Your order number is: @Model</p>
<p>
    Click for New Order @Html.ActionLink("store", "Index1", "MenuItems")
</p>